/* Spotly shared data — ported from src/data/mock.ts */

const CURRENT_USER = {
  name: 'Deon Matongo', firstName: 'Deon',
  email: 'deonmatongo@spotly.app', phone: '+263 77 234 5678',
  initial: 'D', points: 1240, tier: 'Gold', nextTierPoints: 2000,
  memberSince: 'March 2024',
}

const CREDENTIALS = { email: 'deonmatongo@spotly.app', password: '123456' }

const LISTINGS = [
  { id:1, category:'food', type:'restaurant', name:'Amanzi Restaurant', cuisine:'Zimbabwean Fusion · Fine Dining', rating:4.8, reviewCount:642, priceLevel:'$$$$', distance:'1.2 km', address:'225 Enterprise Road, Highlands, Harare', description:"Award-winning fine dining in the heart of Highlands. Amanzi celebrates Zimbabwe's finest ingredients — nyama, fresh bream, and vibrant garden produce — elevated with modern techniques and stunning lake-view terrace.", image:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=500&fit=crop', tags:['Fine Dining','Date Night','Lake View','Zimbabwean'], hours:'Mon–Sun: 12:00 PM – 11:00 PM', timeSlots:['6:00 PM','6:30 PM','7:15 PM','7:30 PM','9:00 PM'], pointsEarned:150, eta:'12 min', popular:true },
  { id:2, category:'food', type:'restaurant', name:'The Braai Deck', cuisine:'Southern African · Braai & Grills', rating:4.6, reviewCount:471, priceLevel:'$$', distance:'0.8 km', address:'Borrowdale Village, Shop 14, Harare', description:"Harare's most beloved braai spot. Hand-cut boerewors, marinated t-bones, and peri-peri chicken grilled over open flame. Cold Zambezi on tap, live marimba on weekends.", image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=500&fit=crop', tags:['Braai','Outdoor','Group-Friendly','Casual'], hours:'Mon–Thu: 11 AM – 10 PM · Fri–Sun: 11 AM – 11 PM', timeSlots:['5:30 PM','6:00 PM','6:45 PM','8:00 PM','8:30 PM'], pointsEarned:80, eta:'20 min', popular:true, menu:[{id:'m1',name:'Boerewors & Pap',desc:'Traditional beef sausage with sadza and relish',price:18.00,image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=200&h=200&fit=crop'},{id:'m2',name:'Peri-Peri Chicken',desc:'Whole spatchcock, flame-grilled, garlic butter',price:22.50,image:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=200&h=200&fit=crop'},{id:'m3',name:'Nyama Choma',desc:'Slow-roasted goat ribs, chimichurri, roasted maize',price:26.00,image:'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=200&h=200&fit=crop'}] },
  { id:3, category:'food', type:'restaurant', name:"Gava's Kitchen", cuisine:'Modern Zimbabwean · Farm-to-Table', rating:4.7, reviewCount:298, priceLevel:'$$$', distance:'1.5 km', address:'4 Newlands Shopping Centre, Newlands, Harare', description:"Chef Gava Muponda's celebrated bistro sources direct from smallholder farms around Harare. The menu changes with the harvest — expect sadza gnocchi, bream ceviche, and seasonal muriwo risotto.", image:'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=500&fit=crop', tags:['Farm-to-Table','Vegetarian-Friendly','Seasonal','Brunch'], hours:'Tue–Sun: 11:30 AM – 10:00 PM', timeSlots:['12:00 PM','12:30 PM','7:00 PM','7:30 PM','8:15 PM'], pointsEarned:100, eta:'18 min', popular:false },
  { id:4, category:'groceries', type:'grocery', name:'Harvest Basket', cuisine:'Groceries · Fresh Produce', rating:4.5, reviewCount:237, priceLevel:'$$', distance:'0.5 km', address:"Sam Levy's Village, Borrowdale, Harare", description:'Premium Zimbabwean groceries, organic Mazowe produce, and artisan pantry staples sourced from local farms — delivered in under 30 minutes across Harare.', image:'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=500&fit=crop', tags:['Organic','Local Produce','Express Delivery'], hours:'Mon–Sun: 7:00 AM – 9:00 PM', eta:'25 min', pointsEarned:50, popular:true, menu:[{id:'g1',name:'Mazowe Oranges (2kg)',desc:'Fresh-picked, sweet & juicy',price:3.50,image:'https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?w=200&h=200&fit=crop'},{id:'g2',name:'Freshly Baked Bread',desc:'Locally milled flour, stone-baked daily',price:2.80,image:'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=200&h=200&fit=crop'},{id:'g3',name:'Biltong Box (250g)',desc:'Premium beef biltong, hand-cured',price:12.00,image:'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=200&h=200&fit=crop'}] },
  { id:5, category:'events', type:'event', name:'Winky D Live in Concert', cuisine:'Live Music · Zimdancehall', rating:4.9, reviewCount:312, priceLevel:'$$$', distance:'3.1 km', address:'Harare International Conference Centre, Harare', description:"Zimbabwe's biggest Zimdancehall artist takes the stage for an unforgettable night. Winky D brings his full band, stunning visuals, and a setlist spanning his iconic career.", image:'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop', tags:['Concert','Zimdancehall','Live Music','Harare'], hours:'Sat 5 Jul 2025', eventDate:'Saturday, 5 July 2025', eventTime:'7:00 PM – 11:30 PM', ticketTiers:[{id:'t1',name:'General Admission',price:25,description:'Standing floor access, general area',color:'#6B7280'},{id:'t2',name:'VIP Seated',price:75,description:'Reserved seating, complimentary drink',color:'#B45309'},{id:'t3',name:'Premium Lounge',price:150,description:'Exclusive lounge, open bar, meet & greet',color:'#15803D'}], pointsEarned:200, eta:'Sat 5 Jul', popular:true },
  { id:6, category:'events', type:'event', name:'Zimbabwe vs Zambia — AFCON Qualifier', cuisine:'Sport · Football', rating:4.8, reviewCount:196, priceLevel:'$$', distance:'4.2 km', address:'National Sports Stadium, Harare', description:"The Warriors take on Zambia in a crucial AFCON qualifier. Experience the electric atmosphere of 65,000 passionate fans as Zimbabwe fight for a place at the continental showpiece.", image:'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&h=500&fit=crop', tags:['Football','Warriors','AFCON','Sport'], hours:'Fri 11 Jul 2025', eventDate:'Friday, 11 July 2025', eventTime:'3:00 PM Kick-off', ticketTiers:[{id:'t1',name:'General Terrace',price:10,description:'Open terrace, general standing',color:'#6B7280'},{id:'t2',name:'Covered Stand',price:20,description:'Covered seating, side view',color:'#1D4ED8'},{id:'t3',name:'VIP Tribune',price:50,description:'Premium central seating, hospitality lounge',color:'#B45309'}], pointsEarned:80, eta:'Fri 11 Jul', popular:true },
  { id:7, category:'events', type:'event', name:'Bustop TV Comedy Night', cuisine:'Comedy · Live Show', rating:4.7, reviewCount:143, priceLevel:'$$', distance:'1.8 km', address:'SASA Comedy Club, Avondale, Harare', description:"Zimbabwe's hottest comedy platform brings its full cast to the stage. Expect two hours of gut-busting sketches, audience participation, and surprise celebrity guests.", image:'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800&h=500&fit=crop', tags:['Comedy','Live Show','Entertainment','Harare'], hours:'Sat 19 Jul 2025', eventDate:'Saturday, 19 July 2025', eventTime:'7:00 PM – 9:30 PM', ticketTiers:[{id:'t1',name:'Standard',price:15,description:'General seating, great view of the stage',color:'#6B7280'},{id:'t2',name:'Front Row',price:35,description:'Premium front-row seats',color:'#7C3AED'}], pointsEarned:60, eta:'Sat 19 Jul', popular:true },
  { id:8, category:'events', type:'event', name:'TEDx Harare 2025', cuisine:'Conference · Ideas', rating:4.9, reviewCount:88, priceLevel:'$$$', distance:'2.3 km', address:'Meikles Hotel, Jason Moyo Ave, Harare', description:'This year\'s theme: "Reimagining Zimbabwe". 12 visionary speakers across tech, arts, and social enterprise. Networking lunch, workshop sessions, and the TEDx afterparty included.', image:'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop', tags:['Conference','TED','Tech','Innovation','Networking'], hours:'Sat 26 Jul 2025', eventDate:'Saturday, 26 July 2025', eventTime:'9:00 AM – 6:00 PM', ticketTiers:[{id:'t1',name:'General',price:45,description:'Full day access, networking lunch included',color:'#6B7280'},{id:'t2',name:'Professional',price:90,description:'Front seating, workshop sessions, afterparty',color:'#0369A1'},{id:'t3',name:'Sponsor Pass',price:200,description:'All access, speaker meet & greet, brand exposure',color:'#B45309'}], pointsEarned:180, eta:'Sat 26 Jul', popular:false },
  { id:9, category:'events', type:'event', name:'Zimbabwe Craft Beer & Food Festival', cuisine:'Festival · Food & Drink', rating:4.6, reviewCount:174, priceLevel:'$$', distance:'2.1 km', address:'Borrowdale Racecourse Grounds, Harare', description:'30+ local craft breweries, artisan food vendors, and live acoustic sets across three stages. Sample everything from Zambezi Pale Ale to mopane-infused stouts.', image:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=500&fit=crop', tags:['Festival','Craft Beer','Food','Outdoor','Live Music'], hours:'Sat–Sun 2–3 Aug 2025', eventDate:'Saturday–Sunday, 2–3 August 2025', eventTime:'12:00 PM – 10:00 PM', ticketTiers:[{id:'t1',name:'Day Pass',price:18,description:'Single day entry, tasting glass included',color:'#6B7280'},{id:'t2',name:'Weekend Pass',price:30,description:'Both days access, tasting glass + 5 tokens',color:'#B45309'},{id:'t3',name:'VIP Weekend',price:65,description:'Both days, VIP lounge, unlimited tastings, t-shirt',color:'#15803D'}], pointsEarned:90, eta:'2–3 Aug', popular:true },
  { id:10, category:'events', type:'event', name:'Harare Jazz & Soul Festival', cuisine:'Live Music · Jazz', rating:4.9, reviewCount:229, priceLevel:'$$$', distance:'3.4 km', address:'Harare Gardens Amphitheatre, Harare', description:"Three nights of world-class jazz, Afro-soul, and R&B under the Harare sky. Featuring Zimbabwe's finest — Oliver Mtukudzi Tribute Band, Patience Musikavanhu, and international headliners.", image:'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=500&fit=crop', tags:['Jazz','Soul','Afro','Festival','Outdoor','Date Night'], hours:'Fri–Sun 8–10 Aug 2025', eventDate:'Friday–Sunday, 8–10 August 2025', eventTime:'6:00 PM – 11:30 PM', ticketTiers:[{id:'t1',name:'General Admission',price:35,description:'Open lawn access, single night',color:'#6B7280'},{id:'t2',name:'Festival Pass',price:85,description:'All 3 nights, reserved seating',color:'#7C3AED'},{id:'t3',name:'Gold Circle',price:160,description:'3 nights, gold circle seating, backstage tour, canapes',color:'#B45309'}], pointsEarned:250, eta:'8–10 Aug', popular:true },
  { id:11, category:'experiences', type:'experience', name:'Msasa Wellness Studio', cuisine:'Wellness · Spa & Float Therapy', rating:4.8, reviewCount:195, priceLevel:'$$$', distance:'2.4 km', address:'17 Msasa Park Drive, Msasa, Harare', description:"Harare's premier wellness destination. Choose from float therapy pods, hot stone massage, and guided meditation — all designed to restore balance in the heart of Msasa.", image:'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&h=500&fit=crop', tags:['Wellness','Spa','Meditation','Solo','Couples'], hours:'Mon–Sun: 8:00 AM – 9:00 PM', timeSlots:['9:00 AM','10:00 AM','11:00 AM','2:00 PM','5:00 PM','7:00 PM'], pointsEarned:130, eta:'Any day', popular:false, price:65 },
  { id:12, category:'experiences', type:'experience', name:'Nyanga Game Drive & Sundowner', cuisine:'Adventure · Wildlife', rating:4.9, reviewCount:312, priceLevel:'$$$$', distance:'12 km', address:'Nyanga National Park, Nyanga', description:'A guided game drive through Nyanga National Park followed by a private sundowner on the escarpment with sweeping valley views. Spot kudu, bushbuck, and baboon in their natural habitat.', image:'https://images.unsplash.com/photo-1534949520000-75a77d39b39b?w=800&h=500&fit=crop', tags:['Safari','Wildlife','Sundowner','Nature','Adventure'], hours:'Daily: Departs 4:00 PM', timeSlots:['4:00 PM'], pointsEarned:200, eta:'Daily 4 PM', popular:true, price:95 },
]

const REVIEWS = [
  { id:1, listingId:1, user:'Farai Ncube', avatar:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face', rating:5, date:'June 2025', text:"Amanzi never disappoints. The bream was cooked to perfection and the terrace at sunset is something truly special. Best fine dining in Harare.", verified:true },
  { id:2, listingId:1, user:'Chiedza Mhuri', avatar:'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=80&h=80&fit=crop&crop=face', rating:4, date:'May 2025', text:"One of the best evenings we've had in the city. The Zimbabwean fusion tasting menu was creative and the service was warm and attentive.", verified:true },
  { id:3, listingId:2, user:'Munashe Dube', avatar:'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face', rating:5, date:'June 2025', text:"Best boerewors in Harare. The Braai Deck gets it right every time — smoky, perfectly seasoned, and the sadza is authentic.", verified:true },
  { id:4, listingId:5, user:'Tatenda Sibanda', avatar:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face', rating:5, date:'Jun 2025', text:"Winky D was absolutely electric. The Premium Lounge experience was worth every dollar — the meet & greet alone was unforgettable.", verified:true },
  { id:5, listingId:9, user:'Rudo Chikwanda', avatar:'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=80&h=80&fit=crop&crop=face', rating:5, date:'May 2025', text:"The craft beer festival exceeded all expectations. So many incredible local breweries and the food was phenomenal.", verified:true },
]

const DEFAULT_BOOKINGS = [
  { id:'b001', listingId:5, listingName:'Winky D Live in Concert', listingImage:'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=240&fit=crop', date:'Sat, 5 Jul 2025', time:'7:00 PM', partySize:2, confirmationCode:'SPT-7823', points:200, status:'confirmed', type:'event' },
  { id:'b002', listingId:1, listingName:'Amanzi Restaurant', listingImage:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=240&fit=crop', date:'Sat, 12 Jul 2025', time:'7:30 PM', partySize:4, confirmationCode:'SPT-4401', points:150, status:'confirmed', type:'restaurant' },
  { id:'b003', listingId:2, listingName:'The Braai Deck', listingImage:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=240&fit=crop', date:'Sat, 14 Jun 2025', time:'7:00 PM', partySize:3, confirmationCode:'SPT-2209', points:80, status:'completed', type:'restaurant', canReview:true },
  { id:'b004', listingId:10, listingName:'Harare Jazz & Soul Festival', listingImage:'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=240&fit=crop', date:'Fri, 24 May 2025', time:'6:00 PM', partySize:2, confirmationCode:'SPT-9934', points:250, status:'completed', type:'event', canReview:false },
]
